// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzgECu8rcHSvhFp0aezzkQ-1DjS3W2lA',
    appId: '1:116098067723:web:3a380873f5849deb4b860e',
    messagingSenderId: '116098067723',
    projectId: 'eventlyst-a3a60',
    authDomain: 'eventlyst-a3a60.firebaseapp.com',
    storageBucket: 'eventlyst-a3a60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLTCjSAEnWYBUTQ1L9n2-jJfphAPYuv8',
    appId: '1:116098067723:android:a35b519451b59aab4b860e',
    messagingSenderId: '116098067723',
    projectId: 'eventlyst-a3a60',
    storageBucket: 'eventlyst-a3a60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzNY8Q9EhneFTK3zBFG6uYlLoJyo0eIA',
    appId: '1:116098067723:ios:e8e47cc49d51bb0c4b860e',
    messagingSenderId: '116098067723',
    projectId: 'eventlyst-a3a60',
    storageBucket: 'eventlyst-a3a60.appspot.com',
    androidClientId: '116098067723-0elco48uev458oo9qg6ijpobfaqpmi61.apps.googleusercontent.com',
    iosClientId: '116098067723-5t1np3617enn2275cfe9r95h491g1n4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzNY8Q9EhneFTK3zBFG6uYlLoJyo0eIA',
    appId: '1:116098067723:ios:b2aadb1a9ab815e74b860e',
    messagingSenderId: '116098067723',
    projectId: 'eventlyst-a3a60',
    storageBucket: 'eventlyst-a3a60.appspot.com',
    androidClientId: '116098067723-0elco48uev458oo9qg6ijpobfaqpmi61.apps.googleusercontent.com',
    iosClientId: '116098067723-avd5m9op16h1efkvn2176oev5o3snc2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
